#!/bin/sh
#
###########################################################################
#
#              Copyright (C) Autelan Technology
#
#This software file is owned and distributed by Autelan Technology 
#
############################################################################
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
#ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
#WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR 
#ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
#(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
#LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
#ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
#(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
#SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#
# eag_init
#
# CREATOR:
# autelan.software.shaojunwu. team
# 
# DESCRIPTION: 
#    init $IPTABLES bash chain!!!
#    for firewall captive portal and asd prev auth
#  filter like!!!
#Chain INPUT (policy ACCEPT 5891 packets, 640047 bytes)
#    pkts      bytes target     prot opt in     out     source               destination         
#
#Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
#    pkts      bytes target     prot opt in     out     source               destination         
#       0        0 ASD_FILTER  0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#       0        0 CP_FILTER  0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#       0        0 FW_FILTER  0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain OUTPUT (policy ACCEPT 1777 packets, 940641 bytes)
#    pkts      bytes target     prot opt in     out     source               destination         
#
#Chain ASD_FILTER (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#       0        0 RETURN     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain CP_FILTER (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#       0        0 RETURN     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain FW_FILTER (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#       0        0 TRAFFIC_CONTROL  0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#       0        0 ACCEPT     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain TRAFFIC_CONTROL (1 references)
#    pkts      bytes target     prot opt in     out     source               destination
#       0        0 RETURN     0    --  *      *       0.0.0.0/0            0.0.0.0/0
#  nat like!!!
#sh-3.1# /opt/bin/$IPTABLES -t nat -nvxL
#Chain PREROUTING (policy ACCEPT 2 packets, 96 bytes)
#    pkts      bytes target     prot opt in     out     source               destination         
#    3877   330542 ASD_DNAT   0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#    3877   330542 CP_DNAT    0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#    4345   373105 FW_DNAT    0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain POSTROUTING (policy ACCEPT 1 packets, 69 bytes)
#    pkts      bytes target     prot opt in     out     source               destination         
#      11     2346 FW_SNAT    0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain OUTPUT (policy ACCEPT 12 packets, 2415 bytes)
#    pkts      bytes target     prot opt in     out     source               destination         
#
#Chain ASD_DNAT (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#    3877   330542 RETURN     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain CP_DNAT (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#    3870   330178 RETURN     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain FW_DNAT (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#    4343   373009 ACCEPT     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#Chain FW_SNAT (1 references)
#    pkts      bytes target     prot opt in     out     source               destination         
#      11     2346 ACCEPT     0    --  *      *       0.0.0.0/0            0.0.0.0/0           
#
#
#############################################################################
IPTABLES="sudo /opt/bin/iptables"

TRAFFIC_CONTROL="TRAFFIC_CONTROL"
FW_FILTER="FW_FILTER"
FW_INPUT="FW_INPUT"
FW_DNAT="FW_DNAT"
FW_SNAT="FW_SNAT"

CP_DNAT="CP_DNAT"
CP_FILTER="CP_FILTER"
MAC_PRE_DNAT="MAC_PRE_DNAT"
MAC_PRE_FILTER="MAC_PRE_FILTER"
EAP_DNAT="EAP_DNAT"
EAP_FILTER="EAP_FILTER"

STRICT_INPUT="STRICT_INPUT"
STRICT_OUTPUT="STRICT_OUTPUT"
STRICT_FORWARD="STRICT_FORWARD"

$IPTABLES -nL $FW_FILTER > /dev/null 2>&1
if [ ! $? -eq 0 ];then
    $IPTABLES -N $FW_FILTER
    $IPTABLES -I FORWARD -j $FW_FILTER
    $IPTABLES -A $FW_FILTER -j ACCEPT
fi

$IPTABLES -nL $TRAFFIC_CONTROL > /dev/null 2>&1
if [ ! $? -eq 0 ];then
    $IPTABLES -N $TRAFFIC_CONTROL
    $IPTABLES -I $FW_FILTER -j $TRAFFIC_CONTROL
    $IPTABLES -A $TRAFFIC_CONTROL -j RETURN
fi

$IPTABLES -nL $FW_INPUT > /dev/null 2>&1
if [ ! $? -eq 0 ];then
    $IPTABLES -N $FW_INPUT
    $IPTABLES -I INPUT -j $FW_INPUT
    $IPTABLES -A $FW_INPUT -j RETURN
fi

$IPTABLES -t nat -nL $FW_DNAT > /dev/null 2>&1
if [ ! $? -eq 0 ];then
    $IPTABLES -t nat -N $FW_DNAT
    $IPTABLES -t nat -I PREROUTING -j $FW_DNAT
    $IPTABLES -t nat -A $FW_DNAT -j ACCEPT
fi

$IPTABLES -t nat -nL $FW_SNAT > /dev/null 2>&1
if [ ! $? -eq 0 ];then
    $IPTABLES -t nat -N $FW_SNAT
    $IPTABLES -t nat -I POSTROUTING -j $FW_SNAT
    $IPTABLES -t nat -A $FW_SNAT -j ACCEPT
fi

$IPTABLES -nL $CP_FILTER > /dev/null 2>&1
if [ ! $? -eq 0 ];then                        
    $IPTABLES -N $CP_FILTER
    $IPTABLES -I FORWARD -j $CP_FILTER
    $IPTABLES -A $CP_FILTER -j RETURN
fi

$IPTABLES -nL $CP_DNAT -t nat > /dev/null 2>&1
if [ ! $? -eq 0 ];then                        
    $IPTABLES -t nat -N $CP_DNAT
    $IPTABLES -t nat -I PREROUTING -j $CP_DNAT
    $IPTABLES -t nat -A $CP_DNAT -j RETURN
fi

$IPTABLES -nL $MAC_PRE_FILTER > /dev/null 2>&1
if [ ! $? -eq 0 ];then                        
    $IPTABLES -N $MAC_PRE_FILTER
    $IPTABLES -I FORWARD -j $MAC_PRE_FILTER
    $IPTABLES -A $MAC_PRE_FILTER -j RETURN
fi

$IPTABLES -nL $MAC_PRE_DNAT -t nat > /dev/null 2>&1
if [ ! $? -eq 0 ];then                        
    $IPTABLES -t nat -N $MAC_PRE_DNAT
    $IPTABLES -t nat -I PREROUTING -j $MAC_PRE_DNAT
    $IPTABLES -t nat -A $MAC_PRE_DNAT -j RETURN
fi

$IPTABLES -nL $EAP_FILTER > /dev/null 2>&1
if [ ! $? -eq 0 ];then                        
    $IPTABLES -N $EAP_FILTER
    $IPTABLES -I FORWARD -j $EAP_FILTER
    $IPTABLES -A $EAP_FILTER -j RETURN
fi

$IPTABLES -nL $EAP_DNAT -t nat > /dev/null 2>&1
if [ ! $? -eq 0 ];then                        
    $IPTABLES -t nat -N $EAP_DNAT
    $IPTABLES -t nat -I PREROUTING -j $EAP_DNAT
    $IPTABLES -t nat -A $EAP_DNAT -j RETURN
fi

$IPTABLES -nL $STRICT_INPUT > /dev/null 2>&1
if [ ! $? -eq 0 ]; then
	$IPTABLES -N $STRICT_INPUT
	$IPTABLES -I INPUT -j $STRICT_INPUT
	$IPTABLES -A $STRICT_INPUT -j RETURN
fi

$IPTABLES -nL $STRICT_OUTPUT > /dev/null 2>&1
if [ ! $? -eq 0 ]; then
	$IPTABLES -N $STRICT_OUTPUT
	$IPTABLES -I OUTPUT -j $STRICT_OUTPUT
	$IPTABLES -A $STRICT_OUTPUT -j RETURN
fi

$IPTABLES -nL $STRICT_FORWARD > /dev/null 2>&1
if [ ! $? -eq 0 ]; then
	$IPTABLES -N $STRICT_FORWARD
	$IPTABLES -I FORWARD -j $STRICT_FORWARD
	$IPTABLES -A $STRICT_FORWARD -j RETURN
fi

mem=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`
cmax=393216
if [ $mem -gt 2000000 ];then
	cmax=1048576
fi
sysctl -w net.nf_conntrack_max=$cmax

#This variable changes the behaviour in the state machine regarding TCP out of window packets
sysctl net.netfilter.nf_conntrack_tcp_be_liberal=1

# wangchao add for the problem that st_set.ko kernel module can't auto load.
ipset -L > /dev/null
insmod /lib/modules/2.6.32.27-Cavium-Octeon/misc/xt_set.ko

exit 0;
