#!/bin/sh

###
# This program is copyright Alec Muffett 1993. The author disclaims all
# responsibility or liability with respect to it's usage or its effect
# upon hardware or computer systems, and maintains copyright as set out
# in the "LICENCE" document which accompanies distributions of Crack v4.0
# and upwards.
###

LC_ALL=C
export LC_ALL

### in case of explosion, invoke "sort" with "-T" option pointing to a lot
### of free space in a directory somewhere.

SORT="sort"
###SORT="sort -T /tmp"

zcat -f $* |
	tr '[A-Z]' '[a-z]' |
	tr -cd '\012[a-z][0-9]' |
	grep -v '^#' |
	grep -v '^$' |
	$SORT |
	uniq
