#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# for a chrooted server: "-u bind -t /var/lib/named"
# Don't modify this line, change or create /etc/default/bind9.
OPTIONS="-c /etc/bind/named.conf"

test -f /etc/default/bind9 && . /etc/default/bind9

test -x /usr/sbin/rndc || exit 0

if [ ! -d /var/cache/bind ]; then
	mkdir /var/cache/bind
fi	
if [ ! -d /var/run/bind ]; then
	mkdir /var/run/bind
fi
if [ ! -d /var/run/bind/run ]; then
	mkdir /var/run/bind/run
fi
if [ ! -d /etc/bind ]; then
	mkdir /etc/bind
fi
case "$1" in
    start)
	echo -n "Starting domain name service: named"

	modprobe capability >/dev/null 2>&1 || true

	# dirs under /var/run can go away on reboots.
	mkdir -p /var/run/bind/run
	chmod 775 /var/run/bind/run
	chown root:bind /var/run/bind/run >/dev/null 2>&1 || true

	if [ ! -x /usr/sbin/named ]; then
	    echo "named binary missing - not starting"
	    exit 1
	fi
	if start-stop-daemon --start --quiet --exec /usr/sbin/named\
		--pidfile /var/run/bind/run/named.pid -- $OPTIONS; then
	    if [ -x /etc/resolvconf ] ; then
		echo "nameserver 127.0.0.1" | /etc/resolvconf -a lo
	    fi
	fi
	echo "."	
    ;;

    stop)
	echo -n "Stopping domain name service: named"
	if [ -x /sbin/resolvconf ]; then
	    /sbin/resolvconf -d lo
	fi
	/usr/sbin/rndc -c /etc/bind/rndc.conf stop
	echo "."	
    ;;

    reload)
	/usr/sbin/rndc -c /etc/bind/rndc.conf reload
    ;;

    restart|force-reload)
	$0 stop
	sleep 2
	$0 start
    ;;
    
    *)
	echo "Usage: /etc/init.d/bind {start|stop|reload|restart|force-reload}" >&2
	exit 1
    ;;
esac

exit 0
